### ISSUE TITLE
possible memory leak

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-pep-steelskin#255]
version fiware-pep-steelskin-0.7.0-28.gcb2213e.noarch

trace found:
```
time=2015-08-25T23:39:24.626Z | lvl=ERROR | corr=de097a32-1991-44e6-be89-24866e3549b6 | trans=de097a32-1991-44e6-be89-24866e3549b6 | op=/v1/updateContext | msg=Error: Can't set headers after they are sent.
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:160:15)
    at Object.cacheAndHold (/opt/pepProxy/lib/services/cacheUtils.js:81:23)
    at retrieveUser (/opt/pepProxy/lib/services/keystoneAuth.js:261:16)
    at /opt/pepProxy/node_modules/async/lib/async.js:656:23
    at /opt/pepProxy/node_modules/async/lib/async.js:610:21
    at /opt/pepProxy/node_modules/async/lib/async.js:249:17
    at iterate (/opt/pepProxy/node_modules/async/lib/async.js:149:13)
    at async.eachSeries (/opt/pepProxy/node_modules/async/lib/async.js:165:9)
    at _asyncMap (/opt/pepProxy/node_modules/async/lib/async.js:248:13)
    at Object.mapSeries (/opt/pepProxy/node_modules/async/lib/async.js:231:23)
```

**Comment by dmoranj** [comment]
Related with https://github.com/telefonicaid/fiware-pep-steelskin/pull/257 and fixed in it, AFAIK.
