### ISSUE TITLE
Proxy crash on Keystone Rejected Token

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/fiware-pep-steelskin#281]
The following behavior has been found randomly in one of our servers:
```
time=2016-02-26T09:04:57.698Z | lvl=ERROR | corr=f885d352-c286-40dd-b978-6ab072f257ba | trans=f885d352-c286-40dd-b978-6ab072f257ba | op=/NGSI10/queryContext | msg=Invalid user toke
n: null
time=2016-02-26T09:04:57.698Z | lvl=ERROR | corr=f885d352-c286-40dd-b978-6ab072f257ba | trans=f885d352-c286-40dd-b978-6ab072f257ba | op=/NGSI10/queryContext | msg=[VALIDATION-GEN-0
03] Error connecting to Keystone authentication: KEYSTONE_AUTHENTICATION_REJECTED: User authentication was rejected with code: 401
time=2016-02-26T09:04:57.699Z | lvl=DEBUG | corr=f885d352-c286-40dd-b978-6ab072f257ba | trans=f885d352-c286-40dd-b978-6ab072f257ba | op=/NGSI10/queryContext | msg=response-time: 13
 statusCode: 401

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property 'serviceId' of undefined
    at processValue (/opt/pepProxy/lib/services/keystoneAuth.js:185:36)
    at EventEmitter.<anonymous> (/opt/pepProxy/lib/services/cacheUtils.js:86:13)
    at EventEmitter.emit (events.js:117:20)
    at /opt/pepProxy/lib/services/cacheUtils.js:99:27
    at /opt/pepProxy/node_modules/async/lib/async.js:544:30
    at Request._callback (/opt/pepProxy/lib/services/keystoneAuth.js:251:17)
    at Request.self.callback (/opt/pepProxy/node_modules/request/request.js:123:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/opt/pepProxy/node_modules/request/request.js:1047:14)
    at Request.emit (events.js:117:20)
```

Version is 0.7.2.

**Comment by dmoranj** [comment]
Duplicated bug.

**Comment by fgalan** [comment]
(Use to be a good practise to include a comment with a link to the duplicated bug for traceability)
